#!/usr/bin/env node

import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const CATALOG_START = "<!-- resource-catalog:start -->";
export const CATALOG_END = "<!-- resource-catalog:end -->";

const COLLECTIONS = [
  { directory: "prompts", heading: "Prompts", type: "Prompt" },
  {
    directory: "openai/instruction-sets",
    heading: "Instruction sets",
    type: "Instruction set",
  },
];

function humanize(value) {
  return value
    .replace(/\.md$/i, "")
    .replace(/[-_]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/\bGit Hub\b/g, "GitHub")
    .replace(/\s+/g, " ")
    .trim();
}

function firstHeading(content) {
  const match = content.match(/^#\s+(.+)$/m);
  return match?.[1].replace(/\s+#+\s*$/, "").trim();
}

function resourceTitle(filePath, content) {
  const filename = path.posix.basename(filePath);

  if (filename.toLowerCase() === "readme.md") {
    const directory = path.posix.basename(path.posix.dirname(filePath));
    return `${firstHeading(content) ?? humanize(directory)} Directory Guide`;
  }

  return humanize(filename);
}

function resourcePurpose(content) {
  const lines = content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "").split(/\r?\n/);
  let inFence = false;
  let paragraph = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (/^(```|~~~)/.test(trimmed)) {
      inFence = !inFence;
      continue;
    }

    if (inFence) {
      continue;
    }

    if (!trimmed) {
      if (paragraph.length) {
        break;
      }
      continue;
    }

    if (
      /^#{1,6}\s/.test(trimmed) ||
      /^<!--/.test(trimmed) ||
      /^---+$/.test(trimmed) ||
      /^\[[^\]]+\]$/.test(trimmed) ||
      /^(?:[-+*]|\d+\.)\s/.test(trimmed) ||
      /^\|/.test(trimmed)
    ) {
      if (paragraph.length) {
        break;
      }
      continue;
    }

    paragraph.push(trimmed);
  }

  const purpose =
    paragraph
      .join(" ")
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      .replace(/\s+/g, " ")
      .trim() || "Open this file for details.";

  return purpose.replace(/:$/, ".");
}

function tableText(value) {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}

function linkText(value) {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("|", "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

function markdownLinkPath(filePath) {
  return filePath.split("/").map(encodeURIComponent).join("/");
}

function resourceRow(resource, collection) {
  const filename = path.posix.basename(resource.path).toLowerCase();
  const type = filename === "readme.md" ? "Directory guide" : collection.type;
  const title = linkText(resourceTitle(resource.path, resource.content));
  const purpose = tableText(resourcePurpose(resource.content));

  return `| [${title}](${markdownLinkPath(resource.path)}) | ${type} | ${purpose} |`;
}

export function renderCatalog(resources) {
  const sections = [];

  for (const collection of COLLECTIONS) {
    const collectionResources = resources
      .filter((resource) => resource.path.startsWith(`${collection.directory}/`))
      .sort((left, right) => left.path.localeCompare(right.path));

    sections.push(`### ${collection.heading}`, "");

    if (!collectionResources.length) {
      sections.push("_No Markdown files are currently available._", "");
      continue;
    }

    sections.push(
      "| Resource | Type | Purpose |",
      "| --- | --- | --- |",
      ...collectionResources.map((resource) => resourceRow(resource, collection)),
      "",
    );
  }

  return [
    CATALOG_START,
    "<!-- Generated by .github/scripts/readme-catalog.mjs; do not edit manually. -->",
    "",
    ...sections,
    CATALOG_END,
  ].join("\n");
}

export function replaceCatalog(readme, resources) {
  const startIndex = readme.indexOf(CATALOG_START);
  const endIndex = readme.indexOf(CATALOG_END);

  if (startIndex < 0 || endIndex < startIndex) {
    throw new Error(
      `README.md must contain complete ${CATALOG_START} and ${CATALOG_END} markers.`,
    );
  }

  const markerEndIndex = startIndex + CATALOG_START.length;
  const lineEnding = readme.startsWith("\r\n", markerEndIndex) ? "\r\n" : "\n";
  const catalog = renderCatalog(resources).replaceAll("\n", lineEnding);

  return (
    readme.slice(0, startIndex) +
    catalog +
    readme.slice(endIndex + CATALOG_END.length)
  );
}

async function markdownFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name);

    const entryStats = await stat(entryPath);

    if (entryStats.isDirectory()) {
      files.push(...(await markdownFiles(entryPath)));
    } else if (entryStats.isFile() && entry.name.toLowerCase().endsWith(".md")) {
      files.push(entryPath);
    }
  }

  return files;
}

export async function collectLocalResources(repositoryRoot) {
  const resources = [];

  for (const collection of COLLECTIONS) {
    const collectionRoot = path.join(repositoryRoot, collection.directory);

    for (const filePath of await markdownFiles(collectionRoot)) {
      resources.push({
        path: path.relative(repositoryRoot, filePath).split(path.sep).join("/"),
        content: await readFile(filePath, "utf8"),
      });
    }
  }

  return resources.sort((left, right) => left.path.localeCompare(right.path));
}

async function main() {
  const repositoryRoot = process.cwd();
  const readmePath = path.join(repositoryRoot, "README.md");
  const current = await readFile(readmePath, "utf8");
  const resources = await collectLocalResources(repositoryRoot);
  const updated = replaceCatalog(current, resources);
  const checkOnly = process.argv.includes("--check");

  if (updated === current) {
    console.log(`README catalog is current (${resources.length} Markdown files).`);
    return;
  }

  if (checkOnly) {
    throw new Error("README catalog is out of date. Run this script without --check.");
  }

  await writeFile(readmePath, updated, "utf8");
  console.log(`Updated README catalog for ${resources.length} Markdown files.`);
}

const invokedPath = process.argv[1]
  ? pathToFileURL(path.resolve(process.argv[1])).href
  : undefined;

if (invokedPath === import.meta.url) {
  await main();
}
